#!/bin/bash

adminProfile=admin

trst=`tput sgr0`
tgrn=`tput setaf 2`
tylw=`tput setaf 3`
tblu=`tput setaf 4`
tdim=`tput dim`


fHelp () {
cat << EOF

${tblu}d${trst} → Describe account (amz d  01234567890)
${tblu}w${trst} → Whoami - enhanced caller identity
${tblu}u${trst} → Unsets AWS_SESSION_TOKEN, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY

EOF
exit
}


if [ -z "$1" ]
  then
        fHelp
	exit
  fi

if [ $1 = "d" ];  then
        aws organizations describe-account --account-id $2 --profile $adminProfile | jq
        exit
fi

if [ $1 = "u" ]; then
        echo -e "🚩 Unsetting Credentials"
        unset AWS_SESSION_TOKEN AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
        exit
fi


fWho() {
	response=$(aws sts get-caller-identity)
	UserId=$(jq -r '.UserId' <<<"$response")
	Account=$(jq -r '.Account' <<<"$response")
	Arn=$(jq -r '.Arn' <<<"$response")
	Name=$(aws organizations describe-account --profile $adminProfile --account-id $Account --query "Account.Name" --output text)

	echo -e "\n${tblu}User${trst}: ${tgrn}$UserId${trst}"
	echo "${tblu}Account${trst}: ${tgrn}$Account${trst}"
	echo "${tblu}Name${trst}: ${tgrn}$Name${trst}"
	echo -e "${tblu}ARN${trst}: ${tgrn}$Arn${trst}\n"
	}


if [ $1 = "w" ]; then
        fWho
	exit
  fi
